services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    container_name: clickhouse_final_project
    environment:
      CLICKHOUSE_DB: "DataEngineeringDB"
      CLICKHOUSE_USER: "admin"
      CLICKHOUSE_PASSWORD: "ClickHouse@2026"
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - clickhouse_final_data:/var/lib/clickhouse
      - clickhouse_final_logs:/var/log/clickhouse

volumes:
  clickhouse_final_data:
  clickhouse_final_logs: