version: 2

models:

  - name: dim_customer
    description: "Customer dimension"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        data_tests:
          - not_null
          - unique

      - name: customer_unique_id
        data_tests:
          - not_null


  - name: dim_product
    description: "Product dimension"
    columns:
      - name: product_id
        description: "Unique product identifier"
        data_tests:
          - not_null
          - unique


  - name: dim_seller
    description: "Seller dimension"
    columns:
      - name: seller_id
        description: "Unique seller identifier"
        data_tests:
          - not_null
          - unique


  - name: dim_geolocation
    description: "Geolocation dimension"
    columns:
      - name: geolocation_zip_code_prefix
        data_tests:
          - not_null


  - name: fact_order
    description: "Order fact table"
    columns:
      - name: order_id
        data_tests:
          - not_null
          - unique

      - name: customer_id
        data_tests:
          - not_null


  - name: fact_order_item
    description: "Order item fact table"
    columns:
      - name: order_id
        data_tests:
          - not_null

      - name: order_item_id
        data_tests:
          - not_null

      - name: product_id
        data_tests:
          - not_null

      - name: seller_id
        data_tests:
          - not_null


  - name: fact_order_payment
    description: "Order payment fact table"
    columns:
      - name: order_id
        data_tests:
          - not_null

      - name: payment_value
        data_tests:
          - not_null


  - name: fact_order_review
    description: "Order review fact table"
    columns:
      - name: review_id
        data_tests:
          - not_null

      - name: order_id
        data_tests:
          - not_null

      - name: review_score
        data_tests:
          - not_null

