name: 'final_project_data_engineering'
version: '1.0.0'
config-version: 2

profile: 'final_project_data_engineering'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  final_project_data_engineering:
    +materialized: table
    +schema: DataEngineeringDB
    
    

    
    
