final_project_data_engineering:
  target: dev

  outputs:
    dev:
      type: clickhouse

      # Koneksi ke ClickHouse
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      secure: false
      threads: 4
      
      # Connection Settings
      threads: "{{ env_var('DBT_THREADS') | int }}"
      connect_timeout: "{{ env_var('DBT_CONNECT_TIMEOUT') | int }}"
      retries: 1