olist_dbt:
  target: dev

  outputs:
    dev:
      type: clickhouse
      schema: DataEngineeringDB
      host: localhost
      port: 8124
      user: admin
      password: "ClickHouse@2026"
      secure: false
      threads: 4